on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      - shell: bash
        run: |
          yarn --frozen-lockfile
          yarn build

      - uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: build/

      - uses: actions/deploy-pages@v1
